# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c80fe6aced6ef7363ae212756227ec38fb16d9b28ca8e68829328d1e98a0e78d658293a7d21723febfce99403e6cb7a2dafec9ef6c739c931cd42c44fa99ff9

test:
  secret_key_base: c4c8d790c8a582da6053ec3204d9d52e47cb6b638779d9d02c001a2c8bf66559347a495c14d582bb7177cb2031bd70ac1210d044141c37700651cb191930fc8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
